// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Delete(arg1) {
  return window['go']['main']['App']['Delete'](arg1);
}

export function GetClips() {
  return window['go']['main']['App']['GetClips']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function TogglePin(arg1) {
  return window['go']['main']['App']['TogglePin'](arg1);
}
