// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Delete(arg1:number):Promise<void>;

export function GetClips():Promise<Array<main.Clip>>;

export function GetVersion():Promise<string>;

export function TogglePin(arg1:number):Promise<void>;
